# Generated by Django 3.0.3 on 2020-03-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('cough', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('breathlessness', models.BooleanField(default=False, verbose_name=((True, 'Yes'), (False, 'No')))),
                ('olderThan60', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('medHistory', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('outsideBD', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('postcode', models.CharField(max_length=4)),
            ],
        ),
    ]
