# Generated by Django 3.0.3 on 2020-03-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('cough', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('cold', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('diarrhea', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('sore_throat', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('body_ache', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('headache', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('breathless', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('fatigue', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('age_group', models.CharField(choices=[('CH', '1-13'), ('TE', '13-19'), ('YN', '20-39'), ('AD', '40-59'), ('OL', '60+')], max_length=2)),
                ('diabetes', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('heart', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('lever', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('smoking', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('cancer_therapy', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('steroid', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('travel_14_days', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('travel_infected_3_month', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('close_contact', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('postcode', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('captcha_score', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('submission_time', models.DateTimeField(auto_now=True)),
                ('browser_id', models.IntegerField(null=True)),
                ('infection_score', models.IntegerField(null=True)),
            ],
        ),
    ]
