# Generated by Django 3.0.3 on 2020-03-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='breathlessness',
            new_name='breathless',
        ),
    ]
