# Generated by Django 3.0.3 on 2020-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200324_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='closecontact',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='breathless',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
