# Generated by Django 3.0.3 on 2020-03-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200324_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
