# Generated by Django 3.0.3 on 2020-03-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200325_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='closecontact',
            new_name='close_contact',
        ),
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='medHistory',
            new_name='med_history',
        ),
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='olderThan60',
            new_name='older_than_60',
        ),
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='outsideBD',
            new_name='outside_BD',
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='captcha_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='infected',
            field=models.CharField(choices=[('SV', 'severe'), ('MD', 'mild'), ('SP', 'spreader'), ('SF', 'safe')], default='SF', max_length=2),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='submission_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
